# Generated by Django 4.0.4 on 2022-05-10 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='mediacontent')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование урока')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации урока')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования урока')),
                ('content', models.TextField(verbose_name='Материалы урока')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
                ('content_audio', models.ManyToManyField(related_name='content_audio', to='main.mediacontent', verbose_name='Аудио урока')),
                ('content_file', models.ManyToManyField(related_name='content_file', to='main.mediacontent', verbose_name='Документы урока')),
            ],
        ),
    ]
