# Generated by Django 4.0.4 on 2022-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('russian', 'Русский язык'), ('literature', 'Литература')], default='russian', max_length=50),
            preserve_default=False,
        ),
    ]
